image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - ./vite-project/package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - cd vite-project
    - npm ci --prefer-offline
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH